services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: subscription-api
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.docker
    ports:
      - "8000:8000"
    networks:
      - backend
    

  db:
    image: postgres:16
    container_name: subscription-db
    env_file:
      - .env.docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 12
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend: