"""add active subscription partial index

Revision ID: 0e900a08fbc3
Revises: 857a07c93d54
Create Date: 2025-12-16 20:29:39.702744

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0e900a08fbc3"
down_revision: Union[str, Sequence[str], None] = "857a07c93d54"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_subscriptions_user_active",
        "subscriptions",
        ["user_id"],
        unique=False,
        postgresql_where=sa.text("is_active = true"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_subscriptions_user_active",
        table_name="subscriptions",
        postgresql_where=sa.text("is_active = true"),
    )
    # ### end Alembic commands ###
